version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /code
    volumes:
       - ./orquestador_backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A app worker --loglevel=info
    working_dir: /code
    volumes:
       - ./orquestador_backend:/code
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

